version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - "${PWD}/db/db.sql:/docker-entrypoint-initdb.d/db.sql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      TZ: "Europe/Moscow"